name: flutter_firebase_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_test:
    sdk: flutter
  file_picker: ^8.3.1
  excel: ^4.0.6
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.1
  firebase_storage: ^12.4.1
  firebase_storage_web: ^3.6.22
  firebase_auth_web: ^5.13.7
  cloud_firestore_web: ^4.4.2
  firebase_core_web: ^2.8.0
  logger: ^2.5.0
  js: ^0.7.1
  path_provider: ^2.0.11
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.9
  intl: ^0.20.2
  dwds: ^24.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14

flutter:
  uses-material-design: true

  assets:
    - assets/FontManifest.json  # Include any custom assets